# Generated by Django 6.0.5 on 2026-05-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='avaliacao_tecnico',
            field=models.TextField(blank=True, null=True, verbose_name='Avaliação do Técnico'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_entrega_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='Possível Data de Entrega'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='servico_planejado',
            field=models.TextField(blank=True, null=True, verbose_name='Serviço que será feito'),
        ),
    ]
