# Generated by Django 6.0.5 on 2026-05-14 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0002_ordemservico_avaliacao_tecnico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='tecnico_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('aberto', 'Em Aberto'), ('aguardando_pecas', 'Aguardando Peças'), ('consertando', 'Consertando'), ('finalizado', 'Finalizado'), ('entregue', 'Entregue')], default='aberto', max_length=20),
        ),
    ]
