# Generated by Django 6.0.5 on 2026-05-25 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0003_ordemservico_tecnico_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordem de Serviços'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente_nome_exibicao',
            field=models.CharField(max_length=100, verbose_name='Nome do Cliente (Exibição)'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minhas_ordens', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao_problema',
            field=models.TextField(verbose_name='Descrição do Problema'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='equipamento',
            field=models.CharField(max_length=100, verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('aberto', 'Em Aberto'), ('aguardando_pecas', 'Aguardando Peças'), ('consertando', 'Consertando'), ('finalizado', 'Finalizado'), ('entregue', 'Entregue')], default='aberto', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
