# Generated by Django 6.0.5 on 2026-05-27 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0004_alter_ordemservico_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('status_momento', models.CharField(max_length=20, verbose_name='Status no Momento')),
                ('descricao_alteracao', models.TextField(verbose_name='O que foi alterado?')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='ordens.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Histórico de Serviço',
                'verbose_name_plural': 'Histórico de Serviços',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
