# Generated by Django 6.0.5 on 2026-05-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0005_historicoordemservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoordemservico',
            name='status_momento',
            field=models.CharField(choices=[('aberto', 'Em Aberto'), ('aguardando_pecas', 'Aguardando Peças'), ('consertando', 'Consertando'), ('finalizado', 'Finalizado'), ('entregue', 'Entregue')], max_length=20, verbose_name='Status no Momento'),
        ),
    ]
