# Generated by Django 6.0.5 on 2026-05-28 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0006_alter_historicoordemservico_status_momento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Entrada do Produto'),
        ),
    ]
