# Generated by Django 6.0.5 on 2026-05-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0007_ordemservico_data_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Estimado (R$)'),
        ),
    ]
