# Generated by Django 6.0.5 on 2026-05-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0008_ordemservico_valor_estimado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicoordemservico',
            options={'ordering': ['-data_alteracao'], 'verbose_name': 'Histórico de Serviço', 'verbose_name_plural': 'Históricos de Serviço'},
        ),
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
    ]
