# Generated by Django 6.0.5 on 2026-09-27 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0019_usuario_login_seguro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='tecnico_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('cargo_sistema__in', ('tecnico', 'tecnico_admin')), ('is_superuser', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo_sistema',
            field=models.CharField(blank=True, choices=[('', 'Cliente comum / sem cargo'), ('atendente', 'Atendente'), ('tecnico', 'Técnico'), ('tecnico_admin', 'Supervisor Técnico'), ('almoxarifado', 'Almoxarifado')], default='', help_text='Use somente para equipe interna. Cliente comum deve ficar sem cargo.', max_length=20, verbose_name='Cargo no Sistema'),
        ),
    ]
