# Generated by Django 6.0.5 on 2026-09-27 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0020_tecnico_operacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('status_os', 'Atualização de ordem'), ('atribuicao_tecnico', 'Atribuição técnica'), ('estoque_baixo', 'Estoque baixo')], max_length=30, verbose_name='Tipo')),
                ('mensagem', models.CharField(max_length=255, verbose_name='Mensagem')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('lida_em', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='ordens.ordemservico', verbose_name='Ordem de Serviço')),
                ('peca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='ordens.peca', verbose_name='Peça')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criada_em'],
            },
        ),
    ]
