# Generated by Django 6.0.5 on 2026-09-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0021_notificacoes_internas'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='resolvida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resolvida em'),
        ),
    ]
