# Generated by Django 6.0.5 on 2026-09-27 23:54

import django.db.models.deletion
import ordens.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0022_resolver_alertas_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=ordens.models.caminho_anexo_ordem)),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_enviados', to=settings.AUTH_USER_MODEL)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='ordens.ordemservico')),
            ],
            options={
                'verbose_name': 'Anexo da ordem',
                'verbose_name_plural': 'Anexos das ordens',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
